//go:build integration

package oracle

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/kamil5b/db2toon/internal/database"
	"github.com/kamil5b/db2toon/pkg/schema"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

func TestOracleSchemaExtraction(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	container, err := testcontainers.Run(ctx, "gvenzl/oracle-free:23-slim-faststart",
		testcontainers.WithExposedPorts("1521/tcp"),
		testcontainers.WithEnv(map[string]string{"ORACLE_PASSWORD": "OraclePassw0rd"}),
		testcontainers.WithWaitStrategy(wait.ForLog("DATABASE IS READY TO USE!").WithStartupTimeout(8*time.Minute)),
	)
	if err != nil {
		t.Fatalf("start Oracle Free container: %v", err)
	}
	t.Cleanup(func() { _ = testcontainers.TerminateContainer(container) })
	host, err := container.Host(ctx)
	if err != nil {
		t.Fatal(err)
	}
	port, err := container.MappedPort(ctx, "1521/tcp")
	if err != nil {
		t.Fatal(err)
	}
	systemDSN := fmt.Sprintf("oracle://system:OraclePassw0rd@%s:%s/FREEPDB1", host, port.Port())
	system, err := New(ctx, systemDSN)
	if err != nil {
		t.Fatalf("connect as system: %v", err)
	}
	t.Cleanup(func() { _ = system.Close(context.Background()) })
	if _, err := system.db.ExecContext(ctx, `CREATE USER app IDENTIFIED BY AppPassw0rd`); err != nil {
		t.Fatalf("create app user: %v", err)
	}
	if _, err := system.db.ExecContext(ctx, `GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO app`); err != nil {
		t.Fatalf("grant app user: %v", err)
	}
	appDSN := fmt.Sprintf("oracle://app:AppPassw0rd@%s:%s/FREEPDB1", host, port.Port())
	extractor, err := New(ctx, appDSN)
	if err != nil {
		t.Fatalf("connect as app: %v", err)
	}
	t.Cleanup(func() { _ = extractor.Close(context.Background()) })
	for _, statement := range []string{
		`CREATE TABLE users (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR2(255) NOT NULL UNIQUE, name VARCHAR2(100), CONSTRAINT users_email_check CHECK (LENGTH(email) > 0))`,
		`CREATE TABLE posts (id NUMBER PRIMARY KEY, author_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE, title VARCHAR2(200) NOT NULL)`,
		`CREATE INDEX posts_title_idx ON posts(title)`,
		`CREATE SEQUENCE invoice_number START WITH 100 INCREMENT BY 5`,
		`CREATE VIEW user_names AS SELECT id, name FROM users`,
		`CREATE FUNCTION user_count RETURN NUMBER AS BEGIN RETURN 1; END;`,
		`CREATE TRIGGER users_audit BEFORE INSERT ON users FOR EACH ROW BEGIN NULL; END;`,
		`INSERT INTO users (email, name) VALUES ('alice@example.com', 'Alice')`,
		`INSERT INTO users (email, name) VALUES ('bob@example.com', 'Bob')`,
	} {
		if _, err := extractor.db.ExecContext(ctx, statement); err != nil {
			t.Fatalf("create fixture: %v", err)
		}
	}
	db, err := extractor.Extract(ctx, database.ExtractOptions{IncludeViews: true, ExampleSample: 2})
	if err != nil {
		t.Fatalf("extract schema: %v", err)
	}
	if len(db.Schemas) != 1 || db.Schemas[0].Name != "APP" {
		t.Fatalf("schemas: %#v", db.Schemas)
	}
	users := findTable(db.Schemas[0].Tables, "USERS")
	posts := findTable(db.Schemas[0].Tables, "POSTS")
	if users.PrimaryKey == nil || len(users.Uniques) != 1 || len(users.Checks) != 1 || len(users.Triggers) != 1 {
		t.Fatalf("users: %#v", users)
	}
	if len(posts.ForeignKeys) != 1 || posts.ForeignKeys[0].OnDelete != "CASCADE" || len(posts.Indexes) != 1 {
		t.Fatalf("posts: %#v", posts)
	}
	if users.Example == nil || len(users.Example.Rows) != 2 {
		t.Fatalf("examples: %#v", users.Example)
	}
	if len(db.Schemas[0].Sequences) != 1 || db.Schemas[0].Sequences[0].Name != "INVOICE_NUMBER" {
		t.Fatalf("sequences: %#v", db.Schemas[0].Sequences)
	}
	if len(db.Schemas[0].Routines) != 1 || db.Schemas[0].Routines[0].Name != "USER_COUNT" {
		t.Fatalf("routines: %#v", db.Schemas[0].Routines)
	}
	view := findTable(db.Schemas[0].Tables, "USER_NAMES")
	if view.Kind != "view" {
		t.Fatalf("view: %#v", view)
	}
}

func findTable(tables []schema.Table, name string) schema.Table {
	for _, table := range tables {
		if table.Name == name {
			return table
		}
	}
	return schema.Table{}
}
