//go:build integration

package oracle

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/kamil5b/db2toon/internal/database"
	"github.com/kamil5b/db2toon/pkg/schema"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

func TestOracleSchemaExtraction(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	container, err := testcontainers.Run(ctx, "gvenzl/oracle-free:23-slim-faststart",
		testcontainers.WithExposedPorts("1521/tcp"),
		testcontainers.WithEnv(map[string]string{"ORACLE_PASSWORD": "OraclePassw0rd"}),
		testcontainers.WithWaitStrategy(wait.ForLog("DATABASE IS READY TO USE!").WithStartupTimeout(8*time.Minute)),
	)
	if err != nil {
		t.Fatalf("start Oracle Free container: %v", err)
	}
	t.Cleanup(func() { _ = testcontainers.TerminateContainer(container) })
	host, err := container.Host(ctx)
	if err != nil {
		t.Fatal(err)
	}
	port, err := container.MappedPort(ctx, "1521/tcp")
	if err != nil {
		t.Fatal(err)
	}
	systemDSN := fmt.Sprintf("oracle://system:OraclePassw0rd@%s:%s/FREEPDB1", host, port.Port())
	system, err := New(ctx, systemDSN)
	if err != nil {
		t.Fatalf("connect as system: %v", err)
	}
	t.Cleanup(func() { _ = system.Close(context.Background()) })
	if _, err := system.db.ExecContext(ctx, `CREATE USER app IDENTIFIED BY AppPassw0rd`); err != nil {
		t.Fatalf("create app user: %v", err)
	}
	if _, err := system.db.ExecContext(ctx, `GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE, CREATE MATERIALIZED VIEW, CREATE DATABASE LINK, CREATE JOB TO app`); err != nil {
		t.Fatalf("grant app user: %v", err)
	}
	appDSN := fmt.Sprintf("oracle://app:AppPassw0rd@%s:%s/FREEPDB1", host, port.Port())
	extractor, err := New(ctx, appDSN)
	if err != nil {
		t.Fatalf("connect as app: %v", err)
	}
	t.Cleanup(func() { _ = extractor.Close(context.Background()) })
	for _, statement := range []string{
		`CREATE TABLE users (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR2(255) NOT NULL UNIQUE, name VARCHAR2(100), CONSTRAINT users_email_check CHECK (LENGTH(email) > 0))`,
		`CREATE TABLE posts (id NUMBER PRIMARY KEY, author_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE, title VARCHAR2(200) NOT NULL)`,
		`CREATE INDEX posts_title_idx ON posts(title)`,
		`CREATE SEQUENCE invoice_number START WITH 100 INCREMENT BY 5`,
		`CREATE TYPE address_type AS OBJECT (street VARCHAR2(100))`,
		`CREATE SYNONYM people FOR users`,
		`CREATE VIEW user_names AS SELECT id, name FROM users`,
		`CREATE MATERIALIZED VIEW user_count_mv AS SELECT COUNT(*) AS total FROM users`,
		`CREATE TABLE audit_events (id NUMBER, created_at DATE) PARTITION BY RANGE (created_at) (PARTITION p2025 VALUES LESS THAN (DATE '2026-01-01'), PARTITION pmax VALUES LESS THAN (MAXVALUE))`,
		`CREATE FUNCTION user_count RETURN NUMBER AS BEGIN RETURN 1; END;`,
		`CREATE PACKAGE user_api AS FUNCTION count_users RETURN NUMBER; END;`,
		`CREATE PACKAGE BODY user_api AS FUNCTION count_users RETURN NUMBER IS BEGIN RETURN 1; END; END;`,
		`CREATE TRIGGER users_audit BEFORE INSERT ON users FOR EACH ROW BEGIN NULL; END;`,
		`CREATE DATABASE LINK remote_db CONNECT TO app IDENTIFIED BY AppPassw0rd USING 'FREEPDB1'`,
		`BEGIN DBMS_SCHEDULER.CREATE_JOB(job_name => 'app_job', job_type => 'PLSQL_BLOCK', job_action => 'BEGIN NULL; END;', enabled => FALSE); END;`,
		`INSERT INTO users (email, name) VALUES ('alice@example.com', 'Alice')`,
		`INSERT INTO users (email, name) VALUES ('bob@example.com', 'Bob')`,
	} {
		if _, err := extractor.db.ExecContext(ctx, statement); err != nil {
			t.Fatalf("create fixture: %v", err)
		}
	}
	db, err := extractor.Extract(ctx, database.ExtractOptions{IncludeViews: true, ExampleSample: 2})
	if err != nil {
		t.Fatalf("extract schema: %v", err)
	}
	if len(db.Schemas) != 1 || db.Schemas[0].Name != "APP" {
		t.Fatalf("schemas: %#v", db.Schemas)
	}
	users := findTable(db.Schemas[0].Tables, "USERS")
	posts := findTable(db.Schemas[0].Tables, "POSTS")
	if users.PrimaryKey == nil || len(users.Uniques) != 1 || len(users.Checks) != 1 || len(users.Triggers) != 1 {
		t.Fatalf("users: %#v", users)
	}
	if len(posts.ForeignKeys) != 1 || posts.ForeignKeys[0].OnDelete != "CASCADE" || len(posts.Indexes) != 1 {
		t.Fatalf("posts: %#v", posts)
	}
	if users.Example == nil || len(users.Example.Rows) != 2 {
		t.Fatalf("examples: %#v", users.Example)
	}
	if len(db.Schemas[0].Sequences) != 1 || db.Schemas[0].Sequences[0].Name != "INVOICE_NUMBER" {
		t.Fatalf("sequences: %#v", db.Schemas[0].Sequences)
	}
	if len(db.Schemas[0].Routines) != 1 || db.Schemas[0].Routines[0].Name != "USER_COUNT" {
		t.Fatalf("routines: %#v", db.Schemas[0].Routines)
	}
	view := findTable(db.Schemas[0].Tables, "USER_NAMES")
	if view.Kind != "view" {
		t.Fatalf("view: %#v", view)
	}
	if len(db.Schemas[0].Types) != 1 || db.Schemas[0].Types[0].Name != "ADDRESS_TYPE" {
		t.Fatalf("types: %#v", db.Schemas[0].Types)
	}
	if len(db.Schemas[0].Synonyms) != 1 || db.Schemas[0].Synonyms[0].Name != "PEOPLE" {
		t.Fatalf("synonyms: %#v", db.Schemas[0].Synonyms)
	}
	for _, want := range []struct{ kind, name string }{{"materialized_view", "USER_COUNT_MV"}, {"package", "USER_API"}, {"package_body", "USER_API"}, {"partitioned_table", "AUDIT_EVENTS"}, {"database_link", "REMOTE_DB"}, {"scheduler_job", "APP_JOB"}} {
		if !hasObject(db.Schemas[0].Objects, want.kind, want.name) {
			t.Fatalf("missing Oracle object %s %s: %#v", want.kind, want.name, db.Schemas[0].Objects)
		}
	}
}

func TestOracleDumpExtraction(t *testing.T) {
	path := filepath.Join(t.TempDir(), "schema.sql")
	const dump = `
CREATE TYPE address_type AS OBJECT (street VARCHAR2(100));
CREATE SEQUENCE invoice_number START WITH 100 INCREMENT BY 5;
CREATE TABLE users (id NUMBER PRIMARY KEY, email VARCHAR2(255) NOT NULL UNIQUE);
CREATE VIEW user_names AS SELECT id, email FROM users;
CREATE MATERIALIZED VIEW user_count_mv AS SELECT COUNT(*) AS total FROM users;
CREATE TABLE audit_events (id NUMBER, created_at DATE) PARTITION BY RANGE (created_at) (PARTITION p2025 VALUES LESS THAN (DATE '2026-01-01'));
CREATE SYNONYM people FOR users;
CREATE FUNCTION user_count RETURN NUMBER AS BEGIN RETURN 1; END;
/
CREATE PROCEDURE list_users AS BEGIN NULL; END;
/
CREATE PACKAGE user_api AS FUNCTION count_users RETURN NUMBER; END;
/
CREATE DATABASE LINK remote_db CONNECT TO app IDENTIFIED BY AppPassw0rd USING 'FREEPDB1';
CREATE TRIGGER users_audit BEFORE INSERT ON users FOR EACH ROW BEGIN NULL; END;
/
`
	if err := os.WriteFile(path, []byte(dump), 0600); err != nil {
		t.Fatal(err)
	}
	extractor, err := NewFromDump(context.Background(), path)
	if err != nil {
		t.Fatal(err)
	}
	db, err := extractor.Extract(context.Background(), database.ExtractOptions{Schemas: []string{"APP"}, IncludeViews: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(db.Schemas) != 1 || len(db.Schemas[0].Tables) != 3 {
		t.Fatalf("database: %#v", db)
	}
	if len(db.Schemas[0].Types) != 1 || len(db.Schemas[0].Sequences) != 1 || len(db.Schemas[0].Synonyms) != 1 || len(db.Schemas[0].Routines) != 2 {
		t.Fatalf("schema objects: %#v", db.Schemas[0])
	}
	if triggers := findTable(db.Schemas[0].Tables, "users").Triggers; len(triggers) != 1 || triggers[0].Name != "users_audit" {
		t.Fatalf("triggers: %#v", triggers)
	}
	for _, want := range []struct{ kind, name string }{{"materialized_view", "user_count_mv"}, {"package", "user_api"}, {"partitioned_table", "audit_events"}, {"database_link", "remote_db"}} {
		if !hasObject(db.Schemas[0].Objects, want.kind, want.name) {
			t.Fatalf("objects: %#v", db.Schemas[0].Objects)
		}
	}
}

func findTable(tables []schema.Table, name string) schema.Table {
	for _, table := range tables {
		if table.Name == name {
			return table
		}
	}
	return schema.Table{}
}

func hasObject(objects []schema.Object, kind, name string) bool {
	for _, object := range objects {
		if object.Kind == kind && object.Name == name {
			return true
		}
	}
	return false
}
