name: test

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: go test ./...
        env:
          CGO_ENABLED: 0

  postgres-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: go test -tags=integration ./internal/database/postgres
        env:
          CGO_ENABLED: 0
