name: test

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: go mod download all
      - run: go mod tidy
      - run: go test ./...

  postgres-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: go mod download all
      - run: go mod tidy
      - run: go test -tags=integration ./cmd/pg2toon
